### ISSUE TITLE
Special Characters addition

### ISSUE THREAD

**Issue by justrelax19** [michaelbironneau/garbler#5]
Can you add all the special characters (^+.=!-_*|,\"<>[]{}`';()@&$#%) in the array of Punctuation or should I raise a PR for that ?

**Comment by michaelbironneau** [comment]
Hi, thanks for the suggestion! If you're up for adding support for additional symbols like you suggest and raising a PR, I'll be happy to merge it. If I don't see anything from you I'll add it myself but it may be a few weeks before I will have time to do this.

**Comment by justrelax19** [comment]
Raised the PR, you can review it.

**Comment by michaelbironneau** [comment]
Thanks, merged.
